In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('product.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           5 non-null      object
 1   Product        5 non-null      object
 2   Region         5 non-null      object
 3   Units Sold     5 non-null      int64
 4   Unit Price     5 non-null      float64
 5   Total Revenue  5 non-null      float64
dtypes: float64(2), int64(1), object(3)
memory usage: 372.0+ bytes

In [4]:
df.head()

         Date   Product Region  Units Sold  Unit Price  Total Revenue
0  2024-01-01  Widget A  North         100        10.0         1000.0
1  2024-01-02  Widget B  South         150        12.5         1875.0
2  2024-01-03  Widget A   East         200        10.0         2000.0
3  2024-01-04  Widget C   West         120        15.0         1800.0
4  2024-01-05  Widget B  North          90        12.5         1125.0

In [21]:
# Calculate the total revenue generated across all sales.
total_revenue = df['Total Revenue'].sum()
print(f"Total Revenue: ${total_revenue:,.2f}")

Total Revenue: $7,800.00

In [8]:
# Group the data by Region and find the total Units Sold for each region.
units_by_region = df.groupby('Region')['Units Sold'].sum()
units_by_region

Region
East     200
North    190
South    150
West     120
Name: Units Sold, dtype: int64

In [ ]:
# Identify the date with the highest Total Revenue.
max_date = df.loc[df['Total Revenue'].idxmax(), 'Date']
max_date

'2024-01-03'

In [ ]:
# Filter and display all records where the Product is "Widget b"
widget_b_sales = df[df['Product'] == 'Widget B']
widget_b_sales

         Date   Product Region  Units Sold  Unit Price  Total Revenue
1  2024-01-02  Widget B  South         150        12.5         1875.0
4  2024-01-05  Widget B  North          90        12.5         1125.0

In [11]:
# Calculate the average Unit Price for each Product.
avg_price_per_product = df.groupby('Product')['Unit Price'].mean()
print(avg_price_per_product)

Product
Widget A    10.0
Widget B    12.5
Widget C    15.0
Name: Unit Price, dtype: float64

In [ ]:
#Add a new column called Revenue per Unit calculated as Total Revenue / Units Sold.
df['Revenue per Unit'] = df['Total Revenue'] / df['Units Sold']

In [18]:
df.columns

Index(['Date', 'Product', 'Region', 'Units Sold', 'Unit Price',
       'Total Revenue', 'Revenue per Unit'],
      dtype='object')

In [19]:
df

,Date,Product,Region,Units Sold,Unit Price,Total Revenue,Revenue per Unit
0,2024-01-01,Widget A,North,100,10.0,1000.0,10.0
1,2024-01-02,Widget B,South,150,12.5,1875.0,12.5
2,2024-01-03,Widget A,East,200,10.0,2000.0,10.0
3,2024-01-04,Widget C,West,120,15.0,1800.0,15.0
4,2024-01-05,Widget B,North,90,12.5,1125.0,12.5